// AUTO-GENERATED by onreza-release
// Run: onreza-release generate-commitlint
// DO NOT EDIT MANUALLY - Changes will be overwritten

import type { UserConfig } from "@commitlint/types";

const config: UserConfig = {
  parserPreset: {
    // Support for feat(scope)!, fix! breaking change syntax
    name: "conventional-changelog-conventionalcommits",
    parserOpts: {
      breakingHeaderPattern: /^(\w*)(?:\((.*)\))?!: (.*)$/,
      headerCorrespondence: ["type", "scope", "subject"],
      headerPattern: /^(\w*)(?:\((.*)\))?!?: (.*)$/,
      noteKeywords: ["BREAKING CHANGE", "BREAKING-CHANGE"],
      revertCorrespondence: ["header", "hash"],
      revertPattern: /^(?:Revert|revert:)\s"?([\s\S]+?)"?\s*This reverts commit (\w*)\./i,
    },
  },

  rules: {
    "body-leading-blank": [2, "always"],
    "body-max-line-length": [2, "always", 100],
    "footer-leading-blank": [2, "always"],
    "footer-max-line-length": [2, "always", 100],
    "header-max-length": [1, "always", 100], // warning
    "header-trim": [2, "always"],
    "scope-empty": [0], // scope optional
    "scope-enum": [2, "always", ["ci", "deps", "docs", "release"]],
    "subject-case": [0], // disabled - any case allowed
    "subject-empty": [2, "never"],
    "subject-full-stop": [2, "never", "."],
    "type-case": [2, "always", "lower-case"],
    "type-empty": [2, "never"],
    "type-enum": [
      2,
      "always",
      ["build", "chore", "ci", "docs", "feat", "fix", "perf", "refactor", "revert", "style", "test"],
    ],
  },
};

export default config;
